src/c/CMakeLists.txt: set pthreads c flag, use cmake var for c99 std
Previously, this would fail in a clean ubuntu 18.04 instance with:

[100%] Linking C executable device-grove
/usr/bin/ld: CMakeFiles/device-grove.dir/main.c.o: undefined reference to symbol 'sem_post@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

This is the simplest way to link to pthreads from this project without
digging into the c-sdk, etc.

Also set the c standard to c99 in a more portable way by setting 
CMAKE_C_STANDARD.

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>